---
# check ufw firewall vs disable ubuntu

- name: Check if ufw package is installed (on Ubuntu).
  command: service ufw status
  args:
    warn: false
  register: ufw_installed
  ignore_errors: true
  changed_when: false
  when:
    - firewall_disable_ufw
  check_mode: false
  tags:
    - iptables-u1604

- name: Disable the ufw firewall (on Ubuntu, if configured).
  service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - firewall_disable_ufw
    - ufw_installed.rc == 0
  tags:
    - iptables-u1604

- name: Install iptables packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - iptables
  tags:
    - iptables-u1604

- name: Flush iptables the first time playbook runs.
  command: >
    iptables -F
    creates=/etc/firewall.bash
  tags:
    - iptables-u1604

- name: Copy firewall script into place.
  template:
    src: firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: 0744
  notify: restart firewall
  tags:
    - iptables-u1604

- name: Copy firewall init script into place.
  template:
    src: firewall.init.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"
  tags:
    - iptables-u1604

- name: Copy firewall systemd unit file into place (for systemd systems).
  template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"
  tags:
    - iptables-u1604

- name: Configure the firewall service.
  service:
    name: firewall
    state: started
    enabled: true
  tags:
    - iptables-u1604

